apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai
  labels:
    app: ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai
  template:
    metadata:
      labels:
        app: ai
    spec:
      containers:
        - name: ai
          image: $(ACR_LOGIN_SERVER)/$(IMAGE_NAME):$(IMAGE_TAG)
          ports:
            - containerPort: 8080
          env:
            - name: OPENAI_API_KEY
              value: "YOUR_API_KEY"
            - name: BASE_URL
              value: "http://ai:8080"
            - name: STORAGE_PATH
              value: "app/ebooks"