apiVersion: apps/v1
kind: Deployment
metadata:
  name: manuscript
  labels:
    app: manuscript
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manuscript
  template:
    metadata:
      labels:
        app: manuscript
    spec:
      containers:
        - name: manuscript
          image: "nextrplue/manuscript:v1"
          ports:
            - containerPort: 8080